### ISSUE TITLE
Do we need the devtools-quick-tips demo?

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/Demos#10]
This repository has a devtools-quick-tips folder: https://github.com/MicrosoftEdge/Demos/tree/main/devtools-quick-tips

This isn't really a demo like the other ones, it doesn't have source code and can't be run. Instead, it's a collection of tips for how to better use DevTools.

For this reason, I'd prefer to remove it from this repository.

To avoid losing the information, I see a couple of possible options:

* Turn these tips into docs (on docs.microsoft.com), if they're not there yet.
* Rely on devtoolstips.org instead, which categorizes tips per browser: https://devtoolstips.org/browser/edge/ (you can also check a box to see only the tips that a particular browser only supports).

What do you think @codepo8 ?

**Comment by codepo8** [comment]
As we have no plan to extend this, I'm happy to remove it. I'm worried about relying on devtoolstips.org as it isn't owned by Microsoft. I know you own it, but things change.

**Comment by captainbrosset** [comment]
That makes sense. I'll go ahead and remove the folder now. And I will check if all tips are present in our docs already, and will open tasks if not.
