### ISSUE TITLE
Network Tutorial "Get Data" failure

### ISSUE THREAD

**Issue by nexusphi** [MicrosoftEdge/Demos#4]
Clicking on the "Get Data" button triggers an error, displayed in the Dev Tools window as "url scheme 'file' not supported, as a result no network activity occurs for this.
![image](https://user-images.githubusercontent.com/96893541/148680951-c395d26f-8ed7-4e73-b4c0-a7821ed775cd.png)

**Comment by captainbrosset** [comment]
I just tested the demo again and it worked for me.

This demo only works when hosted on an HTTP server. So if you try it from this URL it should work: https://microsoftedge.github.io/Demos/network-tutorial/

Looking at your screenshot, it seems like you downloaded the file and just opened it in the browser from the file protocol. This won't work. If you want to use the local file, you can start an HTTP server in the directory that contains it (presumably `D:\Dev\html\webview\Demos-main\network-tutorial\`). There are several ways to do this. One is by installing the [npm package `http-server`](https://www.npmjs.com/package/http-server), and another one is by using [python's simple http server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#running_a_simple_local_http_server).

Let me know if this worked for you.
